---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sa-namespace-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: sa-namespace-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
  namespace: default