---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sa-namespace-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sa-namespace-admin-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
  namespace: default
