apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k3s_user
subjects:
- kind: User
  name: k3s_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
