apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    type: networked
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.44.103
    path: "/data/nfs-share"
    readOnly: false